services:
  shs-db:
    container_name: "shs-db"
    image: "mariadb:11.7"
    restart: "always"
    ports:
      - "3306:3306"
    stdin_open: true
    environment:
      MARIADB_ROOT_PASSWORD: "previetcomrade"
      MARIADB_DATABASE: "shsdb_test"

  shs-cache:
    container_name: "shs-cache"
    image: "redis:7.2.4"
    restart: "always"
    ports:
      - "6379:6379"
    stdin_open: true
    command: >
      --requirepass previetcomrade
